const cont = [
{titolo:'Ambulatori',
image:'img_mhw2/img11.png',
descrizione: 'Nel nostro ospedale è possibile trovare ambulatori con personale sanitario di altissimo livello, tra i migliori in tutta la regione.',
id:'0'},
{titolo:'Vaccini',
image:'img_mhw2/img5.jpeg',
descrizione: 'Il nostro ospedale garantisce il servizio di vaccinazione per tutte le malattie infettive, tra cui, nello specifico, il virus Covid-19.',
id:'1'},
{titolo:'Prenotazioni',
image:'img_mhw2/img6.jpg',
descrizione: 'Per tutte le prenotazioni, ci si può informare, scegliere il tipo di visita e prenotare direttamente via mail',
id:'2'},
{titolo:'Tamponi',
image:'img_mhw2/img7.jpg',
descrizione: 'In questa area si trovano tutte le informazioni relative a tamponi rapidi, molecolari e test sierologici per il virus Covid-19.',
id:'3'},
{titolo:'Telemedicina',
image:'img_mhw2/img9.jpg',
descrizione: 'Il servizio di teleconsulto mette in contatto on-line con gli specialisti del nostro ospedale direttamente da remoto.',
id:'4'},
{titolo:'Ricerca',
image:'img_mhw2/img10.jpg',
descrizione: "Da anni il nostro ospedale punta all'eccellenza nel campo dell'innovazione sanitaria. I nostri ricercatori collaborano con i migliori team della regione.",
id:'5'}
]